### PR TITLE
Fix/pay from offer

### LINKED ISSUE #315: Crash on transferring time from the offer's page
Looks like we're missing one parameter from the payment button on the offer page.

It should be https://www.timeoverflow.org/transfers/new?destination_account_id=22&id=6&offer=12597
and from the button, we link to https://www.timeoverflow.org/transfers/new?id=6&offer=12597. This happens when clicking on the top-right green button on an offer's page.

### PR DESCRIPTION
**Pull request by sauloperez**
## What? Why?

Closes #315.

I forgot to provide the destination of the account in the link to transfer, showed on the offer page. This was fetched in `UsersController#give_time` and later passed to the `give_time` view.

When I did the refactor I forgot to move that from https://github.com/coopdevs/timeoverflow/pull/264/files#diff-4e05ad0d64e6100656b63ad1e78f32c5L67 to the appropriate place (the `OffersController#show`), so that we specify the destination in the `link_to`.

## Introducing view specs :tada: 

Since this had to do also with the view, I thought it was the perfect timing to start doing view specs. I've wanted to add them soon to replace the pseudo pattern matching that we ended up doing in some controller specs to ensure stuff in the views.

I figured it'd be faster to get the test I wanted for the view in this way rather than using the current approach in the controller spec. And I was right. Having the capybara RSpec matchers available, such as `have_link` help a lot. You spend less time checking how does the actual returned HTML look like.

### CODE REVIEW

File: app/controllers/offers_controller.rb [hunk 1]
```diff
@@ -18,4 +18,16 @@ def dashboard
       offers[category] = list if list.present?
     end
   end
+
+  def show
+    super
+
+    if current_user
```
Comment (enricostano) [inline app/controllers/offers_controller.rb]: I'd rather move this check in the view

**Comment by sseerrggii** [comment]
Works fine :+1:
